iris_data = [{'petal_length': '1.4',
              'petal_width': '0.2',
              'sepal_length': '5.1',
              'sepal_width': '3.5',
              'species': 'Iris-setosa'},
             {'petal_length': '1.4',
              'petal_width': '0.2',
              'sepal_length': '4.9',
              'sepal_width': '3',
              'species': 'Iris-setosa'},
             {'petal_length': '1.3',
              'petal_width': '0.2',
              'sepal_length': '4.7',
              'sepal_width': '3.2',
              'species': 'Iris-setosa'},
             {'petal_length': '1.5',
              'petal_width': '0.2',
              'sepal_length': '4.6',
              'sepal_width': '3.1',
              'species': 'Iris-setosa'},
             {'petal_length': '1.4',
              'petal_width': '0.2',
              'sepal_length': '5',
              'sepal_width': '3.6',
              'species': 'Iris-setosa'},
             {'petal_length': '4.7',
              'petal_width': '1.4',
              'sepal_length': '7',
              'sepal_width': '3.2',
              'species': 'Iris-versicolor'},
             {'petal_length': '4.5',
              'petal_width': '1.5',
              'sepal_length': '6.4',
              'sepal_width': '3.2',
              'species': 'Iris-versicolor'},
             {'petal_length': '4.9',
              'petal_width': '1.5',
              'sepal_length': '6.9',
              'sepal_width': '3.1',
              'species': 'Iris-versicolor'},
             {'petal_length': '4',
              'petal_width': '1.3',
              'sepal_length': '5.5',
              'sepal_width': '2.3',
              'species': 'Iris-versicolor'},
             {'petal_length': '4.6',
              'petal_width': '1.5',
              'sepal_length': '6.5',
              'sepal_width': '2.8',
              'species': 'Iris-versicolor'},
             {'petal_length': '6',
              'petal_width': '2.5',
              'sepal_length': '6.3',
              'sepal_width': '3.3',
              'species': 'Iris-virginica'},
             {'petal_length': '5.1',
              'petal_width': '1.9',
              'sepal_length': '5.8',
              'sepal_width': '2.7',
              'species': 'Iris-virginica'},
             {'petal_length': '5.9',
              'petal_width': '2.1',
              'sepal_length': '7.1',
              'sepal_width': '3',
              'species': 'Iris-virginica'},
             {'petal_length': '5.6',
              'petal_width': '1.8',
              'sepal_length': '6.3',
              'sepal_width': '2.9',
              'species': 'Iris-virginica'},
             {'petal_length': '5.8',
              'petal_width': '2.2',
              'sepal_length': '6.5',
              'sepal_width': '3',
              'species': 'Iris-virginica'}]


with open("iris_data.csv", "w") as iris_file:
    header = list(iris_data[0])
    header_string = ",".join(header)
    iris_file.write(header_string + '\n')

    for iris_dict in iris_data:
        values = list(iris_dict.values())
        value_string = ','.join(values)
        iris_file.write(value_string + '\n')
